# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('tools/db_utils', 'tools/db_utils'),
        ('requirements_python310.txt', '.'),
        ('config.py', '.'),
        ('main_app.py', '.'),
        ('wsgi.py', '.'),
        ('gunicorn_config.py', '.'),
        ('gunicorn.conf.py', '.'),
        ('pyproject.toml', '.'),
        ('setup.cfg', '.'),
        ('pyrightconfig.json', '.'),
        ('cspell.json', '.'),
        ('.env', '.'),
        ('app_data', 'app_data'),
    ],
    hiddenimports=[
        'flask',
        'flask_login',
        'flask_session',
        'pymongo',
        'bson',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'webview',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'boto3',
        'botocore',
        'jmespath',
        'python_dateutil',
        's3transfer',
        'six',
        'pandas',
        'numpy',
        'pytz',
        'openpyxl',
        'et_xmlfile',
        'psutil',
        'platform',
        'getpass',
        'csv',
        'io',
        'json',
        'gzip',
        'tempfile',
        'shutil',
        'uuid',
        'pathlib',
        'typing',
        'datetime',
        'logging',
        'traceback',
        'threading',
        'socket',
        'time',
        'os',
        'sys',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='EDF_CatalogoDeTablas',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app/static/favicon.icns' if os.path.exists('app/static/favicon.icns') else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='EDF_CatalogoDeTablas',
)

# Para macOS, crear .app bundle
app = BUNDLE(
    coll,
    name='EDF_CatalogoDeTablas.app',
    icon='app/static/favicon.icns' if os.path.exists('app/static/favicon.icns') else None,
    bundle_identifier='com.edefrutos.catalogodetablas',
    info_plist={
        'CFBundleName': 'EDF CatálogoDeTablas',
        'CFBundleDisplayName': 'EDF CatálogoDeTablas',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '10.13.0',
        'NSRequiresAquaSystemAppearance': False,
    },
)
