[tool.ruff]
target-version = "py38"
line-length = 120

[tool.cspell]
words = [ "api", "aws", "backup", "backups", "bcrypt", "black", "boto3", "catalogos", "catalogotablas", "catálogo", "catálogos", "configuración", "configurar", "cors", "cryptography", "csrf", "diagnosticar", "diagnóstico", "dotenv", "edefrutos", "edf", "escalabilidad", "escalable", "flake8", "flask", "gcp", "gunicorn", "herramientas", "http", "httpdocs", "jinja2", "json", "jwt", "linting", "matplotlib", "migración", "migrar", "mongodb", "monitorear", "monitoreo", "mypy", "métricas", "numpy", "oauth", "pandas", "pillow", "pyc", "pycharm", "pyd", "pymongo", "pyo", "pyright", "pytest", "redirección", "redis", "requests", "restauración", "restore", "ruff", "s3", "sql", "ssl", "tablas", "templates", "testing", "tls", "utilidades", "venv", "verificación", "verificar", "vhosts", "werkzeug", "xml", "xyz",]
ignorePaths = [ "node_modules/**", ".git/**", "venv/**", "__pycache__/**", "*.pyc", "build/**", "dist/**", "*.egg-info/**", ".venv/**", "backups/**", "logs/**", "*.log", "*.md", "*.txt", ".cursorrules", "tools/build/**", "tools/discarded_files_*/**", "app_data/**", "instance/**", "flask_session/**", "uploads/**", "static/uploads/**", "spreadsheets/**", "exportados/**", "imagenes/**", "static/imagenes/**",]

[tool.ruff.lint]
select = [ "E", "W", "F", "I", "B", "C4", "UP",]
ignore = [ "E501", "F401", "F841", "F811", "B008", "B006", "C901", "E203", "E731", "I001", "UP032", "F541", "F821", "B904", "F841",]

[tool.ruff.lint.per-file-ignores]
"app/routes/admin_routes.py" = [ "F401", "F841", "F811", "E501", "I001", "UP032", "F541",]
"tools/test_spell_check_utilities.py" = [ "F401", "F541",]
"tools/quick_test_spell_check_integration.py" = [ "F401", "F541", "UP032",]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = [ "app", "tools", "scripts",]
