# Stub file for google_drive_utils
from typing import Any, Dict, List, Optional

def upload_file_to_drive(file_path: str, folder_id: str) -> Dict[str, Any]: ...
def download_file_from_drive(file_id: str, destination_path: str) -> bool: ...
def list_files_in_folder(folder_id: str) -> List[Dict[str, Any]]: ...
