# Stub file for psutil
from typing import Any, Dict, List, Optional, Tuple

def cpu_percent(interval: Optional[float] = None) -> float: ...
def virtual_memory() -> Any: ...
def disk_usage(path: str) -> Any: ...
def boot_time() -> float: ...
